- lib/views/fact_file/fact_file_index.dart
- lib/views/quiz/quiz_index.dart
- lib/widgets/fact_file/fact_file_tab.dart
- lib/widgets/fact_file/fact_file_tile.dart
Add responsiveness to fact file index
Swapped cross axis count for landscape / portrait 
- landscape 3 across instead of 2
- portrait 2 across instead of 3 
looks better this way
> Responsiveness factfile index

- lib/data/models/activity/activity.dart
- lib/data/models/activity/activity.jorm.dart
- lib/data/models/media_file.dart
- lib/main.dart
- lib/util/data_sync.dart
- lib/util/route_generator.dart
- lib/views/activites/count_activity_view.dart
- lib/views/activites/photograph_activity_view.dart
- lib/views/activites/picture_select_activity_view.dart
- lib/views/activites/picture_tap_activity_view.dart
- lib/views/activites/text_answer_activity_view.dart
- lib/views/home.dart
- lib/widgets/map/map_maker.dart
- lib/widgets/misc/body_text.dart
- lib/widgets/misc/custom_fab.dart
- Map animates to an activity that has been scanned before launching activity
- Activities save to database.
-------
Note: We still need to:
- Sort out the photograph activities save function 
- Improve the views
- Implemented the informational activity
> Integrate database with activity views

- lib/util/screen.dart
- pubspec.yaml
Updated the App version and fixed a mistake - uploaded to the playstore
> Deploy 1.0.1

- lib/views/activites/count_activity_view.dart
- pubspec.yaml
Fixes Issues #69 and #70 also updated the version number so we can push this to the play store for the client demo
> Count activity hot fix

- lib/views/activites/count_activity_view.dart
- lib/views/activites/photograph_activity_view.dart
- lib/views/activites/picture_select_activity_view.dart
- lib/views/activites/picture_tap_activity_view.dart
- lib/views/activites/text_answer_activity_view.dart
> hot fix typo

- lib/data/models/activity/activity.dart
- lib/data/models/quiz/quiz.dart
- lib/views/settings/settings.dart
Implemented reset button in settings:
- Dialog shows to confirm reset
- All activity inputs reset
- All quiz scores removed
> Implement reset progress button

- lib/views/activites/text_answer_activity_view.dart
This pr works towards issue #53 and has been tested on all my devices mentioned 
I have noticed that the keyboard doesn't dismiss when you tap outside so I will go though and check this on all text fields issue #88
> Responsiveness text activity

- lib/views/activites/activity_unlock.dart
- lib/views/activites/picture_select_activity_view.dart
- lib/views/activites/picture_tap_activity_view.dart
- lib/widgets/activities/activity_pass_save_bar.dart
- lib/widgets/activities/selected_photo.dart
This pr works towards issue #53 and has been tested on all my devices mentioned
There is a feature request issue related to ui that would be nice to have for all activity views issue #90
> Responsiveness picture select activity

- lib/views/activites/count_activity_view.dart
- lib/views/activites/photograph_activity_view.dart
- lib/views/activites/picture_select_activity_view.dart
- lib/views/activites/picture_tap_activity_view.dart
- lib/views/activites/text_answer_activity_view.dart
- lib/views/home.dart
- lib/widgets/misc/bottom_back_button.dart
This resolves issue #90 
this has been tested on most views and the rest will be looked it during internal testing and #76 
minor tweaks to some views were made
> Bottom bar mod issue#90

- lib/views/activites/activity_unlock.dart
- lib/views/activites/count_activity_view.dart
- lib/views/activites/photograph_activity_view.dart
- lib/views/activites/picture_select_activity_view.dart
- lib/views/activites/picture_tap_activity_view.dart
- lib/views/activites/text_answer_activity_view.dart
- lib/views/fact_file/fact_file_details.dart
- lib/views/fact_file/fact_file_index.dart
- lib/views/quiz/quiz_result.dart
- lib/views/quiz/quiz_unlock.dart
- lib/views/settings/about.dart
- lib/views/splash.dart
- lib/widgets/activities/activity_pass_save_bar.dart
- lib/widgets/misc/bottom_back_button.dart
- lib/widgets/misc/custom_fab.dart
- lib/widgets/misc/loading_modal_overlay.dart
- lib/widgets/misc/text/body_text.dart
- lib/widgets/quiz/correct_wrong_overlay.dart
- lib/widgets/quiz/image_question.dart
- lib/widgets/quiz/quiz_tile.dart
- lib/widgets/quiz/text_only_question.dart
- lib/widgets/quiz/text_question.dart
resolves issue #88 
also changed keyboard type to number on both activity and quiz unlock and changed body back to bodyText
> Keyboard dismiss issue#88

- lib/views/fact_file/fact_file_details.dart
- lib/widgets/quiz/image_question.dart
- lib/widgets/quiz/text_only_question.dart
- lib/widgets/quiz/text_question.dart
this resolves issue#67
had to replace the body widget containing the label with a stock text widget to give me access to the color property
> change audio button colour when audio is playing

- lib/data/models/factfile/fact_file_entry.dart
- lib/data/models/factfile/fact_file_entry.jorm.dart
- lib/data/models/media_file.dart
- lib/data/models/media_file.jorm.dart
- lib/util/data_sync.dart
- lib/util/image_handler.dart
- lib/util/route_generator.dart
- lib/util/util.dart
- lib/views/activites/count_activity_view.dart
- lib/views/activites/photograph_activity_view.dart
- lib/views/activites/picture_select_activity_view.dart
- lib/views/activites/picture_tap_activity_view.dart
- lib/views/activites/text_answer_activity_view.dart
- lib/views/home.dart
- lib/widgets/activities/activity_pass_save_bar.dart
- pubspec.lock
Still needs to be made responsive.
> Save photographs

- lib/views/activites/photograph_activity_view.dart
- lib/views/splash.dart
- lib/widgets/activities/activity_pass_save_bar.dart
- lib/widgets/misc/custom_fab.dart
This PR resolves issue #53 at long last
there were some minor changes to custom fab and to the splash screen
> Responsiveness photo activity

- .gitignore
- pubspec.lock
modified git ignore as file said not to add to source
We need to decide if we keep these package version changes or wait until later
> upgrade packages as a result of running flutter upgrade

- lib/views/fact_file/fact_file_details.dart
> FactFileReloads#122

- lib/data/models/config.dart
- lib/data/models/config.jorm.dart
- lib/util/data_sync/config_sync.dart
- lib/util/util.dart
- lib/views/activites/photograph_activity_view.dart
- lib/views/settings/settings.dart
- lib/widgets/settings/settings_button.dart
- pubspec.lock
- pubspec.yaml
Created a way to save images to local storage resolving issue #127 
A database variable needs to be implemented and the Util.saveToDevice bool needs to be set from that so that the selections persists
> Save image to gallery issue#127

- android/app/src/main/AndroidManifest.xml
- android/gradle.properties
- lib/env.dart
- lib/util/data_sync/media_sync.dart
- lib/util/data_sync/sync_manager.dart
- lib/views/fact_file/fact_file_details.dart
- lib/views/home.dart
- lib/views/loading_screen.dart
- lib/views/quiz/quiz_result.dart
- lib/widgets/fact_file/fact_file_tile.dart
- pubspec.lock
- pubspec.yaml
This PR replaces the QR scanner with one that works on the trust's tablet.
It also gets the app to request smaller images from the server (300x300 for phones, 500x500 for tablets).
Images are stretched on the fact file view screen to fill the canvas
> Replace qr scanner

- lib/data/models/factfile/fact_file_entry.dart
- lib/util/data_sync/fact_file_sync.dart
- lib/util/data_sync/track_sync.dart
- lib/views/fact_file/fact_file_details.dart
- lib/widgets/fact_file/fact_file_tile.dart
- lib/widgets/fact_file/nuggets/fact_nugget.dart
- lib/widgets/misc/text/body_text.dart
- lib/widgets/misc/text/heading.dart
- lib/widgets/misc/text/sub_heading.dart
This PR alters the display of fact files and also fixes an issue with the data sync not working properly
> Fact file improvements

- lib/util/network_util.dart
- lib/views/quiz/quiz_index.dart
- lib/views/quiz/quiz_result.dart
- lib/views/quiz/quiz_unlock.dart
- lib/views/quiz/quiz_view.dart
- lib/widgets/misc/custom_grid.dart
- lib/widgets/quiz/correct_wrong_overlay.dart
- lib/widgets/quiz/image_question.dart
- lib/widgets/quiz/quiz_text_button.dart
- lib/widgets/quiz/text_only_question.dart
- lib/widgets/quiz/text_question.dart
This PR improves the appearance and display of the quiz views, including the unlock and results views. 
It also adjusts the image result overlay when viewing on a landscape device, as this was overflowing.
> Improve quizzes

- .env.example
- lib/views/quiz/quiz_view.dart
- lib/widgets/quiz/image_question.dart
- lib/widgets/quiz/text_only_question.dart
- lib/widgets/quiz/text_question.dart
stops audio playing when changing question
> Quiz audiofix

- lib/main.dart
- lib/util/noticeboard_sync.dart
Noticeboard should now delete old notices.
> Fix noticeboard bug

- lib/views/fact_file/fact_file_details.dart
- lib/views/fact_file/fact_file_index.dart
- lib/views/settings/noticeboard/noticeboard.dart
- Fact file entries sorted alphabetically before displaying in fact file index
- Swapped icons on the fact file entry audio buttons
- Renamed 'other notices' to 'general notices'
All changes requested by Samuel Grant in ssm-deepcove/website#150
> Minor cosmetic changes

- lib/data/models/quiz/quiz.dart
- lib/data/models/quiz/quiz.jorm.dart
- lib/views/activites/activity_unlock.dart
- lib/views/fact_file/fact_file_index.dart
- lib/views/quiz/quiz_unlock.dart
- lib/views/quiz/quiz_view.dart
- lib/views/settings/noticeboard/noticeboard.dart
This pr shuffles the order each quiz question is presented in each time a quiz is attempted 
also the answers are shuffled for non true/false questions.
> Randomizes the quiz question order and the answer order

- lib/util/network_util.dart
- pubspec.yaml
This should fix the issue with the content download
> Turn off intranet and bump version
